export class ActionType {
    static SET_VALUE = 'SET_VALUE';
    // REMOVE_VALUE = 'REMOVE_VALUE',
    static SET_COMMAND_VALUE = 'SET_COMMAND_VALUE';
    static TOGGLE_POSSIBLE_VALUE = 'TOGGLE_POSSIBLE_VALUE';
    static SET_COMMAND_MODE = 'SET_COMMAND_MODE';
    // GENERATE_NEW_SUDOKU = 'GENERATE_NEW_SUDOKU',
}
